from .user_route import user_route
from .author_route import author_route
from .book_route import book_route
from .book_author_route import book_author_route
from .book_copy_route import book_copy_route
from .borrowed_route import borrowed_route
from .library_card_route import library_card_route
from .publisher_route import publisher_route
from .visitor_route import visitor_route
from .visitor_photo_route import visitor_photo_route
from .entry_log_route import entry_log_route
from .dashboard_route import dashboard_route
from .member_route import member_route
from .reserve_route import reserve_route
from .queue_route import queue_route
from .wishlist_route import wishlist_route
from .report_route import report_route
from .campus_route import campus_route
from .setting_route import setting_route
